name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  devsecops:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # use nodejs and/or python installation based on your application code base 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (Node.js)
      run: npm install || true

    - name: Install dependencies (Python)
      run: pip install -r requirements.txt || true

    - name: Snyk IaC Scan
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Open Source (SCA)
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test

    - name: Snyk Code (SAST)
      uses: snyk/actions/code@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'http://example.com'  # Replace with your deployed app URL
